version: '0.1'

services:
  server:
    build: ./server/
    ports:
     - "8080:8080"
  db:
    container_name: db
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'test_pass'
      POSTGRES_DB: 'some_db'
      # MYSQL_ROOT_PASSWORD: 'test_pass'
      # MYSQL_USER: 'root'
      # MYSQL_PASS: 'pass'
    ports:
      - "5432:5432"
    volumes:
      - /opt/mysql_data:/var/lib/mysql