version: '0.1'

services:
  frontend-person:
    build: ./frontend
    links:
      - server-person
    ports:
     - "80:80"
  server-person:
    build: ./server
    links:
      - db-person
    ports:
     - "8080:8080"
  db-person:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_DATABASE: 'some_db'
      # MYSQL_USER: 'root'
      # MYSQL_PASS: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql