version: '0.1'

services:
  server:
    build: .
    ports:
     - "8080:8080"
  db:
    container_name: mysql
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      # MYSQL_USER: 'root'
      # MYSQL_PASS: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql